### ISSUE TITLE
Unitalized constant error

### ISSUE THREAD

**Issue by sbehrens** [jodyalbritton/Rails-Blog-Tutorial#1]
Hello,

I am recieving the following error after following all the steps.  The error occurs when doing rake db:migrate:

rake db:migrate

ssss@ubuntu-dev:~/Rails-Blog-Tutorial$ rake db:migrate
==  DeviseCreateUsers: migrating ==============================================
-- create_table(:users)
   -> 0.0255s
-- add_index(:users, :email, {:unique=>true})
   -> 0.0175s
-- add_index(:users, :reset_password_token, {:unique=>true})
   -> 0.0173s
==  DeviseCreateUsers: migrated (0.0627s) =====================================

==  AddUsernameToUser: migrating ==============================================
-- add_column(:users, :username, :string)
   -> 0.0063s
-- ad...
...
An error has occurred, all later migrations canceled:

uninitialized constant DeviseCreateAdminUsers::AdminUser

Any ideas on what the issue may be?

**Comment by MOctavio** [comment]
I'm having that same issue, I belive the solution requires a class named AdminUser in the models (probabbly is missing) but right now I'm not sure what to put inside that class.

Update:

I have created under Models a file named admin_user.rb with a 'standard' devise content.

class AdminUser < ActiveRecord::Base
   devise :database_authenticatable, 
      :recoverable, :rememberable, :trackable, :validatable
   attr_accessible :email, :password, :password_confirmation, :remember_me
 end

**Comment by jodyalbritton** [comment]
Sorry for the delayed response. I think @moctavio is correct. I will push a fix for this by tonight.

**Comment by jodyalbritton** [comment]
I have updated the code. I also need to update the instructions if your planning on using this. 

You will need to create a user - 

/users/new

After you have a  user navigate to 

/site_config

To set the site name and owner name.

/posts/new  for you first posts
